global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8035938463:AAHnTVjXBugT5dXKwuQdCPwoMGmllV2SZ5Q'
        chat_id: 1092017156
        send_resolved: true
        message: |
          {{ if eq .Status "firing" }}🔴 ИНЦИДЕНТ{{ else }}✅ ВОССТАНОВЛЕНО{{ end }}

          {{ range .Alerts }}
          *Сервис:* {{ .Labels.job }}
          *Алерт:* {{ .Labels.alertname }}
          *Описание:* {{ .Annotations.description }}
          *Время:* {{ .StartsAt.Local.Format "02.01.2006 15:04:05" }} (UTC+5)
          {{ end }}
        parse_mode: 'Markdown'
