apiVersion: v1
kind: ConfigMap
metadata:
  name: mooztau-config
  namespace: mooztau
data:
  DB_HOST: "postgres"
  DB_NAME: "mooztau_db"
  DB_USER: "postgres"
  VITE_MOCK: "false"
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB: "mooztau_chat"
