apiVersion: v1
kind: Secret
metadata:
  name: mooztau-secret
  namespace: mooztau
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "changeme_replace_in_production"
  GRAFANA_PASSWORD: "admin"
  MONGO_USER: "mooztau"
  MONGO_PASSWORD: "mooztau_pwd"
