global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "orders-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["orders:8001"]

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8002"]

  - job_name: "finance-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["finance:8003"]
