[mooztau]
mooztau-server ansible_host=213.155.22.46 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[mooztau:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
deploy_path=/home/ubuntu/mooztau/Mooztau_back
domain=medhome.kz
